project:
  type: website
  output-dir: PMO_Docs
  render: 
    - index.qmd
    - format/FormatOverview.qmd
    - format/FormatExample.qmd
    - format/FormatOverviewAdvanced.qmd
    - format/DevelopmentOfFormat.qmd
    - PMO_Ecosystem/Pmo_in_the_ecosystem.qmd
    - Tools_Installation/pmotools-python_installation.qmd
    - pmotools-python-usages/pmotools-python.qmd
    - pmotools-python-usages/extracting_allele_tables.qmd
    - pmotools-python-usages/subsetting_from_PMO.qmd
    - pmotools-python-usages/handling_multiple_pmos.qmd
    - pmotools-python-usages/validating_pmos.qmd
    - pmotools-python-usages/getting_basic_info_from_pmo.qmd
    - pmotools-python-usages/extracting_panel_info_from_pmo.qmd
    - pmotools-python-usages-notebooks/getting_basic_info_on_pmo_file.ipynb
    - pmotools-python-usages-notebooks/build_pmo.ipynb
    - References.qmd

website:
  title: "Portable Microhaplotype Object (PMO)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Format Info
        menu: 
          - text: <span class='menuTitle'>Overview of Format</span>
          - text: "------------"
          - href: format/FormatOverview.qmd
          - href: PMO_Ecosystem/Pmo_in_the_ecosystem.qmd
          - text: <span class='menuTitle'>History of Format Development</span>
          - text: "------------"
          - href: format/DevelopmentOfFormat.qmd
          - text: <span class='menuTitle'>Overview of Format For Bioinformaticians</span>
          - text: "------------"
          - href: format/FormatExample.qmd
          - href: format/FormatOverviewAdvanced.qmd
      - text: "Tools Installation"
        menu:
          - href: Tools_Installation/pmotools-python_installation.qmd
      - text: "pmotools-python usages"
        menu: 
          - text: <span class='menuTitle'>Command line interface</span>
          - text: "------------"
          - text: <span class='menuTitle'>pmotools-python</span>
          - href: pmotools-python-usages/pmotools-python.qmd
          - text: <span class='menuTitle'>Extracting out of PMO</span>
          - href: pmotools-python-usages/extracting_allele_tables.qmd
          - text: <span class='menuTitle'>Subset PMO</span>
          - href: pmotools-python-usages/subsetting_from_PMO.qmd
          - text: <span class='menuTitle'>Getting sub info from PMO</span>
          - href: pmotools-python-usages/getting_basic_info_from_pmo.qmd
          - href: pmotools-python-usages/extracting_panel_info_from_pmo.qmd
          - text: <span class='menuTitle'>Handling Multiple PMOs</span>
          - href: pmotools-python-usages/handling_multiple_pmos.qmd
          - text: <span class='menuTitle'>Validating PMO files</span>
          - href: pmotools-python-usages/validating_pmos.qmd
          - text: "------------"
          - text: <span class='menuTitle'>Python interface</span>
          - href: pmotools-python-usages-notebooks/getting_basic_info_on_pmo_file.ipynb
          - href: pmotools-python-usages-notebooks/build_pmo.ipynb
    right: 
      - text: "Resources"
        menu: 
          - text: "References"
            href: References.qmd
      - icon: github
        menu:
          - text: <span class='menuTitle'>Documentation</span>
          - text: Documentation Source Code
            href:  https://github.com/PlasmoGenEpi/PMO_Docs
          - text: Comment or Report an issue for Documentation  
            href:  https://github.com/PlasmoGenEpi/PMO_Docs/issues
          - text: "------------"
          - text: <span class='menuTitle'>pmotools-python</span>
          - text: pmotools-python Source Code
            href:  https://github.com/PlasmoGenEpi/pmotools-python/tree/develop
          - text: Comment or Report an issue for pmotools-python  
            href:  https://github.com/PlasmoGenEpi/pmotools-python/issues


format:
  html:
    theme: cosmo
    css: styles.css
    fig-height: 10
    fig-width: 15
    fig-dpi: 300
    toc: true
    toc-depth: 5 # default is 3
    toc-title: Contents
    anchor-sections: true
    smooth-scroll: true
    highlight-style: dracula
    page-layout: full
    code-fold: show
    code-tools: true
    code-link: true
    bibliography: [references.bib]
    biblio-style: apalike
    back-to-top-navigation: true
    
editor: source
